#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
if [[ "$OSTYPE" == "msys" ]]; then
	py -3 "$SCRIPTPATH"/tools/build_scripts/pmbuild.py "$@"
else
	python3 "$SCRIPTPATH"/tools/build_scripts/pmbuild.py "$@"
fi