#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
if [[ "$OSTYPE" == "msys" ]]; then
	"$SCRIPTPATH"/third_party/pmbuild/pmbuild "$@"
else
	"$SCRIPTPATH"/third_party/pmbuild/pmbuild "$@"
fi