#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
../tools/premake/premake5 xcode4 --renderer=opengl
python3 ../tools/build_shaders.py glsl osx
python3 ../tools/build_textures.py
python3 ../tools/build_audio.py