#ifndef _renderer_definitions_h
#define _renderer_definitions_h

#include <d3d11_1.h>

//raster state
#define PEN_FILL_SOLID									D3D11_FILL_SOLID
#define PEN_FILL_WIREFRAME								D3D11_FILL_WIREFRAME

#define PEN_CULL_NONE									D3D11_CULL_NONE
#define PEN_CULL_FRONT									D3D11_CULL_FRONT
#define PEN_CULL_BACK									D3D11_CULL_BACK

//pen custom
#define PEN_DEFAULT_RT	1
#define PEN_DEFAULT_DS	2

//usage
#define PEN_USAGE_DEFAULT								D3D11_USAGE_DEFAULT
#define PEN_USAGE_IMMUTABLE								D3D11_USAGE_IMMUTABLE
#define PEN_USAGE_DYNAMIC								D3D11_USAGE_DYNAMIC
#define PEN_USAGE_STAGING								D3D11_USAGE_STAGING

//bind flags
#define	PEN_BIND_VERTEX_BUFFER							D3D11_BIND_VERTEX_BUFFER
#define	PEN_BIND_INDEX_BUFFER							D3D11_BIND_INDEX_BUFFER
#define	PEN_BIND_CONSTANT_BUFFER						D3D11_BIND_CONSTANT_BUFFER
#define	PEN_BIND_SHADER_RESOURCE						D3D11_BIND_SHADER_RESOURCE
#define	PEN_BIND_STREAM_OUTPUT							D3D11_BIND_STREAM_OUTPUT
#define	PEN_BIND_RENDER_TARGET							D3D11_BIND_RENDER_TARGET
#define	PEN_BIND_DEPTH_STENCIL							D3D11_BIND_DEPTH_STENCIL
#define	PEN_BIND_UNORDERED_ACCESS						D3D11_BIND_UNORDERED_ACCESS
#define	PEN_BIND_DECODER								D3D11_BIND_DECODER
#define	PEN_BIND_VIDEO_ENCODER							D3D11_BIND_VIDEO_ENCODER

//cpu access flags
#define	D3D11_CPU_ACCESS_WRITE							D3D11_CPU_ACCESS_WRITE
#define	D3D11_CPU_ACCESS_READ							D3D11_CPU_ACCESS_READ
#define	D3D11_CPU_ACCESS_FLAG							D3D11_CPU_ACCESS_FLAG

//primitive topology
#define	PEN_PT_POINTLIST								D3D11_PRIMITIVE_TOPOLOGY_POINTLIST
#define	PEN_PT_LINELIST									D3D11_PRIMITIVE_TOPOLOGY_LINELIST
#define	PEN_PT_LINESTRIP								D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP
#define	PEN_PT_TRIANGLELIST								D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST
#define	PEN_PT_TRIANGLESTRIP							D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP

//format
#define	PEN_FORMAT_UNKNOWN								DXGI_FORMAT_UNKNOWN
#define	PEN_FORMAT_R32G32B32A32_TYPELESS				DXGI_FORMAT_R32G32B32A32_TYPELESS
#define	PEN_FORMAT_R32G32B32A32_FLOAT					DXGI_FORMAT_R32G32B32A32_FLOAT
#define	PEN_FORMAT_R32G32B32A32_UINT					DXGI_FORMAT_R32G32B32A32_UINT
#define	PEN_FORMAT_R32G32B32A32_SINT					DXGI_FORMAT_R32G32B32A32_SINT
#define	PEN_FORMAT_R32G32B32_TYPELESS					DXGI_FORMAT_R32G32B32_TYPELESS
#define	PEN_FORMAT_R32G32B32_FLOAT						DXGI_FORMAT_R32G32B32_FLOAT
#define	PEN_FORMAT_R32G32B32_UINT						DXGI_FORMAT_R32G32B32_UINT
#define	PEN_FORMAT_R32G32B32_SINT						DXGI_FORMAT_R32G32B32_SINT
#define	PEN_FORMAT_R16G16B16A16_TYPELESS				DXGI_FORMAT_R16G16B16A16_TYPELESS
#define	PEN_FORMAT_R16G16B16A16_FLOAT					DXGI_FORMAT_R16G16B16A16_FLOAT
#define	PEN_FORMAT_R16G16B16A16_UNORM					DXGI_FORMAT_R16G16B16A16_UNORM
#define	PEN_FORMAT_R16G16B16A16_UINT					DXGI_FORMAT_R16G16B16A16_UINT
#define	PEN_FORMAT_R16G16B16A16_SNORM					DXGI_FORMAT_R16G16B16A16_SNORM
#define	PEN_FORMAT_R16G16B16A16_SINT 					DXGI_FORMAT_R16G16B16A16_SINT 
#define	PEN_FORMAT_R32G32_TYPELESS						DXGI_FORMAT_R32G32_TYPELESS
#define	PEN_FORMAT_R32G32_FLOAT							DXGI_FORMAT_R32G32_FLOAT
#define	PEN_FORMAT_R32G32_UINT							DXGI_FORMAT_R32G32_UINT
#define	PEN_FORMAT_R32G32_SINT							DXGI_FORMAT_R32G32_SINT
#define	PEN_FORMAT_R32G8X24_TYPELESS					DXGI_FORMAT_R32G8X24_TYPELESS
#define	PEN_FORMAT_D32_FLOAT_S8X24_UINT					DXGI_FORMAT_D32_FLOAT_S8X24_UINT
#define	PEN_FORMAT_R32_FLOAT_X8X24_TYPELESS				DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS
#define	PEN_FORMAT_X32_TYPELESS_G8X24_UINT				DXGI_FORMAT_X32_TYPELESS_G8X24_UINT
#define	PEN_FORMAT_R10G10B10A2_TYPELESS					DXGI_FORMAT_R10G10B10A2_TYPELESS
#define	PEN_FORMAT_R10G10B10A2_UNORM					DXGI_FORMAT_R10G10B10A2_UNORM
#define	PEN_FORMAT_R10G10B10A2_UINT						DXGI_FORMAT_R10G10B10A2_UINT
#define	PEN_FORMAT_R11G11B10_FLOAT						DXGI_FORMAT_R11G11B10_FLOAT
#define	PEN_FORMAT_R8G8B8A8_TYPELESS					DXGI_FORMAT_R8G8B8A8_TYPELESS
#define	PEN_FORMAT_R8G8B8A8_UNORM						DXGI_FORMAT_R8G8B8A8_UNORM
#define	PEN_FORMAT_R8G8B8A8_UNORM_SRGB					DXGI_FORMAT_R8G8B8A8_UNORM_SRGB
#define	PEN_FORMAT_R8G8B8A8_UINT						DXGI_FORMAT_R8G8B8A8_UINT
#define	PEN_FORMAT_R8G8B8A8_SNORM						DXGI_FORMAT_R8G8B8A8_SNORM
#define	PEN_FORMAT_R8G8B8A8_SINT						DXGI_FORMAT_R8G8B8A8_SINT
#define	PEN_FORMAT_R16G16_TYPELESS						DXGI_FORMAT_R16G16_TYPELESS
#define	PEN_FORMAT_R16G16_FLOAT							DXGI_FORMAT_R16G16_FLOAT
#define	PEN_FORMAT_R16G16_UNORM							DXGI_FORMAT_R16G16_UNORM
#define	PEN_FORMAT_R16G16_UINT							DXGI_FORMAT_R16G16_UINT
#define	PEN_FORMAT_R16G16_SNORM							DXGI_FORMAT_R16G16_SNORM
#define	PEN_FORMAT_R16G16_SINT							DXGI_FORMAT_R16G16_SINT
#define	PEN_FORMAT_R32_TYPELESS							DXGI_FORMAT_R32_TYPELESS
#define	PEN_FORMAT_D32_FLOAT							DXGI_FORMAT_D32_FLOAT
#define	PEN_FORMAT_R32_FLOAT							DXGI_FORMAT_R32_FLOAT
#define	PEN_FORMAT_R32_UINT								DXGI_FORMAT_R32_UINT
#define	PEN_FORMAT_R32_SINT								DXGI_FORMAT_R32_SINT
#define	PEN_FORMAT_R24G8_TYPELESS						DXGI_FORMAT_R24G8_TYPELESS
#define	PEN_FORMAT_D24_UNORM_S8_UINT					DXGI_FORMAT_D24_UNORM_S8_UINT
#define	PEN_FORMAT_R24_UNORM_X8_TYPELESS				DXGI_FORMAT_R24_UNORM_X8_TYPELESS
#define	PEN_FORMAT_X24_TYPELESS_G8_UINT					DXGI_FORMAT_X24_TYPELESS_G8_UINT
#define	PEN_FORMAT_R8G8_TYPELESS						DXGI_FORMAT_R8G8_TYPELESS
#define	PEN_FORMAT_R8G8_UNORM							DXGI_FORMAT_R8G8_UNORM
#define	PEN_FORMAT_R8G8_UINT							DXGI_FORMAT_R8G8_UINT
#define	PEN_FORMAT_R8G8_SNORM							DXGI_FORMAT_R8G8_SNORM
#define	PEN_FORMAT_R8G8_SINT							DXGI_FORMAT_R8G8_SINT
#define	PEN_FORMAT_R16_TYPELESS							DXGI_FORMAT_R16_TYPELESS
#define	PEN_FORMAT_R16_FLOAT							DXGI_FORMAT_R16_FLOAT
#define	PEN_FORMAT_D16_UNORM							DXGI_FORMAT_D16_UNORM
#define	PEN_FORMAT_R16_UNORM							DXGI_FORMAT_R16_UNORM
#define	PEN_FORMAT_R16_UINT								DXGI_FORMAT_R16_UINT
#define	PEN_FORMAT_R16_SNORM							DXGI_FORMAT_R16_SNORM
#define	PEN_FORMAT_R16_SINT								DXGI_FORMAT_R16_SINT
#define	PEN_FORMAT_R8_TYPELESS							DXGI_FORMAT_R8_TYPELESS
#define	PEN_FORMAT_R8_UNORM								DXGI_FORMAT_R8_UNORM
#define	PEN_FORMAT_R8_UINT								DXGI_FORMAT_R8_UINT
#define	PEN_FORMAT_R8_SNORM								DXGI_FORMAT_R8_SNORM
#define	PEN_FORMAT_R8_SINT								DXGI_FORMAT_R8_SINT
#define	PEN_FORMAT_A8_UNORM								DXGI_FORMAT_A8_UNORM
#define	PEN_FORMAT_R1_UNORM								DXGI_FORMAT_R1_UNORM
#define	PEN_FORMAT_R9G9B9E5_SHAREDEXP					DXGI_FORMAT_R9G9B9E5_SHAREDEXP
#define	PEN_FORMAT_R8G8_B8G8_UNORM						DXGI_FORMAT_R8G8_B8G8_UNORM
#define	PEN_FORMAT_G8R8_G8B8_UNORM						DXGI_FORMAT_G8R8_G8B8_UNORM
#define	PEN_FORMAT_BC1_TYPELESS							DXGI_FORMAT_BC1_TYPELESS
#define	PEN_FORMAT_BC1_UNORM							DXGI_FORMAT_BC1_UNORM
#define	PEN_FORMAT_BC1_UNORM_SRGB 						DXGI_FORMAT_BC1_UNORM_SRGB 
#define	PEN_FORMAT_BC2_TYPELESS							DXGI_FORMAT_BC2_TYPELESS
#define	PEN_FORMAT_BC2_UNORM							DXGI_FORMAT_BC2_UNORM
#define	PEN_FORMAT_BC2_UNORM_SRGB						DXGI_FORMAT_BC2_UNORM_SRGB
#define	PEN_FORMAT_BC3_TYPELESS							DXGI_FORMAT_BC3_TYPELESS
#define	PEN_FORMAT_BC3_UNORM							DXGI_FORMAT_BC3_UNORM
#define	PEN_FORMAT_BC3_UNORM_SRGB						DXGI_FORMAT_BC3_UNORM_SRGB
#define	PEN_FORMAT_BC4_TYPELESS 						DXGI_FORMAT_BC4_TYPELESS 
#define	PEN_FORMAT_BC4_UNORM							DXGI_FORMAT_BC4_UNORM
#define	PEN_FORMAT_BC4_SNORM							DXGI_FORMAT_BC4_SNORM
#define	PEN_FORMAT_BC5_TYPELESS 						DXGI_FORMAT_BC5_TYPELESS 
#define	PEN_FORMAT_BC5_UNORM							DXGI_FORMAT_BC5_UNORM
#define	PEN_FORMAT_BC5_SNORM							DXGI_FORMAT_BC5_SNORM
#define	PEN_FORMAT_B5G6R5_UNORM							DXGI_FORMAT_B5G6R5_UNORM
#define	PEN_FORMAT_B5G5R5A1_UNORM						DXGI_FORMAT_B5G5R5A1_UNORM
#define	PEN_FORMAT_B8G8R8A8_UNORM						DXGI_FORMAT_B8G8R8A8_UNORM
#define	PEN_FORMAT_B8G8R8X8_UNORM 						DXGI_FORMAT_B8G8R8X8_UNORM 
#define	PEN_FORMAT_R10G10B10_XR_BIAS_A2_UNORM			DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM
#define	PEN_FORMAT_B8G8R8A8_TYPELESS					DXGI_FORMAT_B8G8R8A8_TYPELESS
#define	PEN_FORMAT_B8G8R8A8_UNORM_SRGB					DXGI_FORMAT_B8G8R8A8_UNORM_SRGB
#define	PEN_FORMAT_B8G8R8X8_TYPELESS					DXGI_FORMAT_B8G8R8X8_TYPELESS
#define	PEN_FORMAT_B8G8R8X8_UNORM_SRGB					DXGI_FORMAT_B8G8R8X8_UNORM_SRGB
#define	PEN_FORMAT_BC6H_TYPELESS						DXGI_FORMAT_BC6H_TYPELESS
#define	PEN_FORMAT_BC6H_UF16							DXGI_FORMAT_BC6H_UF16
#define	PEN_FORMAT_BC6H_SF16							DXGI_FORMAT_BC6H_SF16
#define	PEN_FORMAT_BC7_TYPELESS							DXGI_FORMAT_BC7_TYPELESS
#define	PEN_FORMAT_BC7_UNORM							DXGI_FORMAT_BC7_UNORM
#define	PEN_FORMAT_BC7_UNORM_SRGB						DXGI_FORMAT_BC7_UNORM_SRGB
#define	PEN_FORMAT_AYUV 								DXGI_FORMAT_AYUV 
#define	PEN_FORMAT_Y410 								DXGI_FORMAT_Y410 
#define	PEN_FORMAT_Y416 								DXGI_FORMAT_Y416 
#define	PEN_FORMAT_NV12 								DXGI_FORMAT_NV12 
#define	PEN_FORMAT_P010 								DXGI_FORMAT_P010 
#define	PEN_FORMAT_P016 								DXGI_FORMAT_P016 
#define	PEN_FORMAT_420_OPAQUE							DXGI_FORMAT_420_OPAQUE
#define	PEN_FORMAT_YUY2									DXGI_FORMAT_YUY2
#define	PEN_FORMAT_Y210									DXGI_FORMAT_Y210
#define	PEN_FORMAT_Y216									DXGI_FORMAT_Y216
#define	PEN_FORMAT_NV11									DXGI_FORMAT_NV11
#define	PEN_FORMAT_AI44									DXGI_FORMAT_AI44
#define	PEN_FORMAT_IA44									DXGI_FORMAT_IA44
#define	PEN_FORMAT_P8									DXGI_FORMAT_P8
#define	PEN_FORMAT_A8P8									DXGI_FORMAT_A8P8
#define	PEN_FORMAT_B4G4R4A4_UNORM						DXGI_FORMAT_B4G4R4A4_UNORM
#define	PEN_FORMAT_FORCE_UINT							DXGI_FORMAT_FORCE_UINT

//sampler filters
#define PEN_FILTER_MIN_MAG_MIP_POINT								D3D11_FILTER_MIN_MAG_MIP_POINT
#define PEN_FILTER_MIN_MAG_POINT_MIP_LINEAR							D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT					D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_MIN_POINT_MAG_MIP_LINEAR							D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR
#define PEN_FILTER_MIN_LINEAR_MAG_MIP_POINT 						D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT 
#define PEN_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR					D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_MIN_MAG_LINEAR_MIP_POINT							D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_MIN_MAG_MIP_LINEAR								D3D11_FILTER_MIN_MAG_MIP_LINEAR
#define PEN_FILTER_ANISOTROPIC										D3D11_FILTER_ANISOTROPIC
#define PEN_FILTER_COMPARISON_MIN_MAG_MIP_POINT						D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT
#define PEN_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR				D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT		D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR				D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR
#define PEN_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT				D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT
#define PEN_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR		D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT				D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR					D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR
#define PEN_FILTER_COMPARISON_ANISOTROPIC							D3D11_FILTER_COMPARISON_ANISOTROPIC
#define PEN_FILTER_MINIMUM_MIN_MAG_MIP_POINT						D3D11_FILTER_MINIMUM_MIN_MAG_MIP_POINT
#define PEN_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR					D3D11_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT			D3D11_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR					D3D11_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR
#define PEN_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT					D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT
#define PEN_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR			D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT					D3D11_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR						D3D11_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR
#define PEN_FILTER_MINIMUM_ANISOTROPIC								D3D11_FILTER_MINIMUM_ANISOTROPIC
#define PEN_FILTER_MAXIMUM_MIN_MAG_MIP_POINT						D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_POINT
#define PEN_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR					D3D11_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT			D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR					D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR
#define PEN_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT					D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT
#define PEN_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR			D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR
#define PEN_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT					D3D11_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT
#define PEN_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR						D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR
#define PEN_FILTER_MAXIMUM_ANISOTROPIC								D3D11_FILTER_MAXIMUM_ANISOTROPIC

//texture address mode
#define PEN_TEXTURE_ADDRESS_WRAP									D3D11_TEXTURE_ADDRESS_WRAP
#define PEN_TEXTURE_ADDRESS_MIRROR									D3D11_TEXTURE_ADDRESS_MIRROR
#define PEN_TEXTURE_ADDRESS_CLAMP									D3D11_TEXTURE_ADDRESS_CLAMP
#define PEN_TEXTURE_ADDRESS_BORDER									D3D11_TEXTURE_ADDRESS_BORDER
#define PEN_TEXTURE_ADDRESS_MIRROR_ONCE								D3D11_TEXTURE_ADDRESS_MIRROR_ONCE

//comparison function
#define	PEN_COMPARISON_NEVER										D3D11_COMPARISON_NEVER
#define	PEN_COMPARISON_LESS											D3D11_COMPARISON_LESS
#define	PEN_COMPARISON_EQUAL 										D3D11_COMPARISON_EQUAL 
#define	PEN_COMPARISON_LESS_EQUAL									D3D11_COMPARISON_LESS_EQUAL
#define	PEN_COMPARISON_GREATER 										D3D11_COMPARISON_GREATER 
#define	PEN_COMPARISON_NOT_EQUAL									D3D11_COMPARISON_NOT_EQUAL
#define	PEN_COMPARISON_GREATER_EQUAL								D3D11_COMPARISON_GREATER_EQUAL
#define	PEN_COMPARISON_ALWAYS 										D3D11_COMPARISON_ALWAYS 

//blending factors
#define	PEN_BLEND_ZERO												D3D11_BLEND_ZERO
#define	PEN_BLEND_ONE												D3D11_BLEND_ONE
#define	PEN_BLEND_SRC_COLOR 										D3D11_BLEND_SRC_COLOR 
#define	PEN_BLEND_INV_SRC_COLOR										D3D11_BLEND_INV_SRC_COLOR
#define	PEN_BLEND_SRC_ALPHA 										D3D11_BLEND_SRC_ALPHA 
#define	PEN_BLEND_INV_SRC_ALPHA										D3D11_BLEND_INV_SRC_ALPHA
#define	PEN_BLEND_DEST_ALPHA										D3D11_BLEND_DEST_ALPHA
#define	PEN_BLEND_INV_DEST_ALPHA									D3D11_BLEND_INV_DEST_ALPHA
#define	PEN_BLEND_DEST_COLOR 										D3D11_BLEND_DEST_COLOR 
#define	PEN_BLEND_INV_DEST_COLOR									D3D11_BLEND_INV_DEST_COLOR
#define	PEN_BLEND_SRC_ALPHA_SAT										D3D11_BLEND_SRC_ALPHA_SAT
#define	PEN_BLEND_BLEND_FACTOR										D3D11_BLEND_BLEND_FACTOR
#define	PEN_BLEND_INV_BLEND_FACTOR									D3D11_BLEND_INV_BLEND_FACTOR
#define	PEN_BLEND_SRC1_COLOR										D3D11_BLEND_SRC1_COLOR
#define	PEN_BLEND_INV_SRC1_COLOR									D3D11_BLEND_INV_SRC1_COLOR
#define	PEN_BLEND_SRC1_ALPHA 										D3D11_BLEND_SRC1_ALPHA 
#define	PEN_BLEND_INV_SRC1_ALPHA									D3D11_BLEND_INV_SRC1_ALPHA

//blend ops
#define	PEN_BLEND_OP_ADD											D3D11_BLEND_OP_ADD
#define	PEN_BLEND_OP_SUBTRACT										D3D11_BLEND_OP_SUBTRACT
#define	PEN_BLEND_OP_REV_SUBTRACT									D3D11_BLEND_OP_REV_SUBTRACT
#define	PEN_BLEND_OP_MIN											D3D11_BLEND_OP_MIN
#define	PEN_BLEND_OP_MAX											D3D11_BLEND_OP_MAX

//queries
#define PEN_QUERY_BEGIN												1
#define PEN_QUERY_END												2

#define PEN_QUERY_EVENT 0
#define PEN_QUERY_OCCLUSION (PEN_QUERY_EVENT + 1)
#define PEN_QUERY_TIMESTAMP (PEN_QUERY_OCCLUSION + 1)
#define PEN_QUERY_TIMESTAMP_DISJOINT (PEN_QUERY_TIMESTAMP + 1)
#define PEN_QUERY_PIPELINE_STATISTICS (PEN_QUERY_TIMESTAMP_DISJOINT + 1)
#define PEN_QUERY_OCCLUSION_PREDICATE  (PEN_QUERY_PIPELINE_STATISTICS + 1)
#define PEN_QUERY_SO_STATISTICS  (PEN_QUERY_OCCLUSION_PREDICATE + 1)
#define PEN_QUERY_SO_OVERFLOW_PREDICATE  (PEN_QUERY_SO_STATISTICS + 1)
#define PEN_QUERY_SO_STATISTICS_STREAM0  (PEN_QUERY_SO_OVERFLOW_PREDICATE + 1)
#define PEN_QUERY_SO_OVERFLOW_PREDICATE_STREAM0  (PEN_QUERY_SO_STATISTICS_STREAM0 + 1)
#define PEN_QUERY_SO_STATISTICS_STREAM1  (PEN_QUERY_SO_OVERFLOW_PREDICATE_STREAM0 + 1)
#define PEN_QUERY_SO_OVERFLOW_PREDICATE_STREAM1  (PEN_QUERY_SO_STATISTICS_STREAM1 + 1)
#define PEN_QUERY_SO_STATISTICS_STREAM2  (PEN_QUERY_SO_OVERFLOW_PREDICATE_STREAM1 + 1)
#define PEN_QUERY_SO_OVERFLOW_PREDICATE_STREAM2  (PEN_QUERY_SO_STATISTICS_STREAM2 + 1)
#define PEN_QUERY_SO_STATISTICS_STREAM3  (PEN_QUERY_SO_OVERFLOW_PREDICATE_STREAM2 + 1)
#define PEN_QUERY_SO_OVERFLOW_PREDICATE_STREAM3  (PEN_QUERY_SO_STATISTICS_STREAM3 + 1)

//misc flags
#define PEN_RESOURCE_MISC_GENERATE_MIPS 0x1L
#define PEN_RESOURCE_MISC_SHARED  0x2L
#define PEN_RESOURCE_MISC_TEXTURECUBE  0x4L
#define PEN_RESOURCE_MISC_DRAWINDIRECT_ARGS 0x10L
#define PEN_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS 0x20,
#define PEN_RESOURCE_MISC_BUFFER_STRUCTURED 0x40L
#define PEN_RESOURCE_MISC_RESOURCE_CLAMP 0x80L
#define PEN_RESOURCE_MISC_SHARED_KEYEDMUTEX 0x100L
#define PEN_RESOURCE_MISC_GDI_COMPATIBLE 0x200L
#define PEN_RESOURCE_MISC_SHARED_NTHANDLE 0x800L
#define PEN_RESOURCE_MISC_RESTRICTED_CONTENT 0x1000L
#define PEN_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE 0x2000L
#define PEN_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE_DRIVER 0x4000L
#define PEN_RESOURCE_MISC_GUARDED 0x8000L
#define PEN_RESOURCE_MISC_TILE_POOL 0x20000L
#define PEN_RESOURCE_MISC_TILED  0x40000L

#endif